### ISSUE TITLE
Update file lists

### ISSUE THREAD

**Issue by tomsons26** [bdamer/br-mixer#1]
Related to a CnCNet project i was researching Westwood's games and their file formats.
While i was doing that i started mapping out the mix filenames and that included Blade Runner.
Since i'm no programmer, mainly a artist i have no need for a xcc git fork but i asked a teammate, Blade to push the filename lists to his fork.
https://github.com/OmniBlade/xcc/blob/master/xcc/data/blade%20mix%20description.txt
https://github.com/OmniBlade/xcc/blob/master/xcc/data/blade%20tlk%20description.txt

The mix filenames are hashed with the same method that TD uses.
The Mix name list is complete, should include all the other language files too, but no guarantee, i know i did map some but not all but the difference is really just one to three letters.

The TLKs are just mixes, but the method the filenames are hashed is different, so XCC won't detect them but those names were logged with Sysinternals Process Monitor so they should be correct.

i know it uses the actor list for those http://westwoodbladerunner.blogspot.com/p/actors.html detailed here and you can proably find some code in MadMoose's code.
https://github.com/madmoose/scummvm/tree/bladerunner

**Comment by bdamer** [comment]
Thanks for the info! I've included the list of filenames - looks like it now resolves all of them correctly.
