### ISSUE TITLE
VQA Header info

### ISSUE THREAD

**Issue by tomsons26** [bdamer/br-mixer#3]
VQA:
;IFF stuff
4   IFFChunk
2   Unknown?
2   Unknown?
; VQAHeader
8   Signature
4   RStartPos
2   Version
2   Flags
2   Frames
2   ImageWidth
2   ImageHeight
1   BlockWidth
1   BlockHeight
1   FPS
1   Groupsize
2   Num1Colors
2   CBentries
2   Xpos
2   Ypos
2   MaxFramesize
2   SampleRate
1   Channels
1   BitsPerSample
2   Streams
12  FutureUse

This header is from the debug build of Westwoods Monopoly i have, the debug symbols only contain the VQA header tho, not sure what does the IFF part contain.
The number is how many bytes its long.
FutureUse is used in TS and later so it is made use of in BR. No one has any info on what it contains afik.
Not sure if that is 12. In Poly's symbols its two bytes but obviously there's a lot more looking at the later game files.

**Comment by bdamer** [comment]
Thanks for the info - it matches what I have for the header in https://github.com/bdamer/br-mixer/blob/master/src/vqafile.h

Loading the header is working fine, as far as I can tell, but there are issues decoding the content.
